--- Makefile.orig
+++ Makefile
@@ -238,6 +238,7 @@
        cat ${KERNEL_SRC}/debian.master/config/config.common.ubuntu ${KERNEL_SRC}/debian.master/config/${ARCH}/config.common.${ARCH} ${KERNEL_SRC}/debian.master/config/${ARCH}/config.flavour.generic > ${KERNEL_CFG_ORG}
        cd ${KERNEL_SRC}; patch -p1 < ../uname-version-timestamp.patch
        cd ${KERNEL_SRC}; patch -p1 <../bridge-patch.diff
+       cd ${KERNEL_SRC}; patch -p1 <../0007-rmrr-patch-proxmox.5.0.patch
        #cd ${KERNEL_SRC}; patch -p1 <../bridge-forward-ipv6-neighbor-solicitation.patch
        #cd ${KERNEL_SRC}; patch -p1 <../add-empty-ndo_poll_controller-to-veth.patch
        cd ${KERNEL_SRC}; patch -p1 <../override_for_missing_acs_capabilities.patch
